### ISSUE TITLE
没有sampler文件

### ISSUE THREAD

**Issue by 1944xpp** [Keke921/H2T#2]
作者能给一下sampler吗，十分感谢

**Comment by Keke921** [comment]
稍等，我在整理代码，今天就传好cifar的

**Comment by Keke921** [comment]
> 作者能给一下sampler吗，十分感谢

稍等，我在整理代码，今天就传好cifar100

**Comment by 1944xpp** [comment]
好的，谢谢

**Comment by 1944xpp** [comment]
from .sampler import ClassAwareSampler
ModuleNotFoundError: No module named 'datasets.sampler'
作者大大您好，新上传的代码还是没有sampler.py文件

**Comment by Keke921** [comment]
> from .sampler import ClassAwareSampler ModuleNotFoundError: No module named 'datasets.sampler' 作者大大您好，新上传的代码还是没有sampler.py文件

现在好啦，再看下。inaturalist的data list 太大了，它一断掉后面的文件都跟着不更新了，sorry，之前没注意。这次应该好啦

**Comment by 1944xpp** [comment]
嗯嗯，有了，感谢感谢
