### ISSUE TITLE
作者你好，可以提供一下项目的环境吗。

### ISSUE THREAD

**Issue by asphyxia-bit** [Keke921/H2T#3]
我在项目中没有找到配置文件

**Comment by Keke921** [comment]
> 我在项目中没有找到配置文件

不好意思，之前没注意到这个issue。
因为我们的方法是加在别的方法上的，所以具体运行时要看所加的方法的运行环境，所以没有特别列出项目环境。这个repo提供的代码也不限制pytorch版本，我在pytorch1.11以及pytorch2上都运行过。
其他的就是常见的包，运行时如果报错，可以根据报缺少的包进行安装。
